
package com.grupobancolombia.intf.producto.deposito.transferenciacuentasdeposito.enlace.v1;

import javax.xml.ws.WebFault;
import com.grupobancolombia.intf.producto.deposito.transferenciacuentasdeposito.v1.BusinessException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "businessException", targetNamespace = "http://grupobancolombia.com/intf/Producto/Deposito/TransferenciaCuentasDeposito/V1.0")
public class BusinessExceptionMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessExceptionMsg(String message, BusinessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessExceptionMsg(String message, BusinessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.grupobancolombia.intf.producto.deposito.transferenciacuentasdeposito.v1.BusinessException
     */
    public BusinessException getFaultInfo() {
        return faultInfo;
    }

}
